const CONSTANTS = {
  PROJECT_ROUTES: {
    PRIVATE_ROUTES: {
      HOME: "/",
      EXPLORE: "/explore",
      MESSAGES: "/messages",
      NOTIFICATIONS: "/notifications",
      PROFILE: "/profile",
      SETTINGS: "/settings",
    },
    PUBLIC_ROUTES: {
      LOGIN: "/login",
      REGISTER: "/register",
    },
  },
  API_ROUTES: {
    LOGIN: "/user/login",
    SIGNUP: "/user/register",
    GOOGLE_SIGNIN: "/user/google-signin",
    CREATE_POST: "/post",
    EDIT_POST: "/post",
    GET_ALL_POST: "/post",
    GET_ALL_PUBLIC_POST: "/post/publicPosts",
    GENERATE_CAPTION: "/post/generate-caption",
    TOGGLE_LIKE: "/post/toggleLike",
    TOGGLE_SAVE: "/post/toggleSave",
    FETCH_COMMENTS: "/post/comments",
    ADD_COMMENT: "/post/comments",
    SEARCH_USERS: "/friend/searchUsers",
    PROFILE_POSTS: "/profile/posts",
    PROFILE_PHOTOS: "/profile/photos",
    PROFILE_SAVED: "/profile/saved",
    EDIT_PROFILE_DETAILS: "/profile",
    GET_PROFILE_DETAILS: "/profile",
    VALIDATE_USERNAME: "/profile/validateUsername",
    SEND_REQUEST: "/friend/requests",
    GET_NOTIFICATIONS: "/notifications",
    GET_UN_READ_COUNT: "/notifications/unReadCount",
    GET_REQUEST_LIST: "/friend/requests",
    RESPOND_TO_REQ: "/friend/requests",
    GET_FRIENDS_LIST: "/friend/friends",
    REMOVE_FRIEND: "/friend/friends",
    CREATE_STORY: "/story",
    REMOVE_STORY: "/story",
    GET_STORIES: "/story",
    SEARCH_FRIENDS: "/chat/searchFriends",
    GET_CHANNELS_LIST: "/chat/channels",
    GET_CHANNEL_MESSAGES: "/chat/messages",
    SEND_MESSAGE: "/chat/messages",
    DELETE_MESSAGE: "/chat/messages",
    EDIT_MESSAGE: "/chat/messages",
    CHANNEL_DETAILS: "/chat/channelDetails",
    CREATE_CHANNEL: "/chat/channels",
    MESSAGE_SEEN: "/chat/seen",
    EDIT_CHANNEL_DETAILS: "/chat/channelDetails",
  },
  JIO_SAAVN_API: "https://saavn.dev/api/search/songs?query=",
  LOCAL_STORAGE_KEY: "authToken",
  SOCKET_EVENTS: {
    CONNECT: "connect",
    DISCONNECT: "disconnect",
    ERROR: "SOCKET_ERROR",
    MSG_RECEIVED: "Message-Received",
    USER_TYPING: "User-Typing",
    USER_NOT_TYPING: "User-Not-Typing",
    MSG_EDITED: "Message-Edited",
    MSG_DELETED: "Message-Deleted",
    CHAT_OPENED: "Chat-Opened",
    CHAT_CLOSED: "Chat-Closed",
    USER_PRESENCE_CHANGE: "User-Presence-Change",
    MSG_NOTIFICATION: "Message-Notification",
    MSG_SEEN_NOTIFICATION: "Message-Seen",
  },
};

export default CONSTANTS;
